/cone_detection_node:
    ros__parameters:
        # Topic names
        lidar_points_topic: "/lidar/Lidar1"
        camera_image_topic: "/fsds/cam1/image_color"
        # Model params
        model_path: "/home/ros/ws/src/cone_detection/models/Yolov8n1280.onnx"
        classes: [
            "seg_orange_cone", 
            "unknown_cone", 
            "yellow_cone", 
            "seg_large_orange_cone", 
            "seg_blue_cone", 
            "seg_unknown_cone", 
            "seg_yellow_cone", 
            "blue_cone", 
            "orange_cone", 
            "large_orange_cone"
        ]
        width: 1280
        height: 1280
        iou_threshold: 0.5
        rect_confidence_threshold: 0.4
        cuda_enable: true
        log_severity_level: 3
        intra_op_num_threads: 1
        # Lidar-Camera fusion params
        # | Ouster OS1-64: 131072 point/rotate,
        # | ang_res_x: 0.17578125 (for 90 deg), ang_res_y: 0.3516
        max_len: 30.0
        min_len: 0.01
        max_fov: 2.3554
        min_fov: 0.7854
        ang_res_x: 0.17578125
        ang_res_y: 0.3516
        max_ang_w: 90.0
        max_ang_h: 22.5
        interp_value: 10.0
        max_var: 50.0
        # Lidar-Camera fusion matrices
        camera_matrix: [
            640.0, 0.0  , 640.0, 0.0,
            0.0  , 640.0, 640.0, 0.0,
            0.0  , 0.0  , 1.0  , 0.0
        ]
        rotation_matrix: [
            1.0, 0.0, 0.0,
            0.0, 1.0, 0.0,
            0.0, 0.0, 1.0
        ]
        # | translation_matrix: [ 1.5, 0.0, -0.4]
        translation_matrix: [ 0.0, 0.1, 0.0]
