/cone_detection_node:
    ros__parameters:
        # The current event (mission) 
        # Possible values (lowercase):
        # - "acceleration" : acceleration test
        # - "skidpad"      : figure-eight handling test
        # - "autocross"    : obstacle avoidance (slalom)
        # - "trackdrive"   : multiple laps on a track
        # - "endurance"    : long-distance reliability and efficiency test
        mission: "trackdrive"
        # Topic names
        lidar_points_topic: "/lidar/Lidar1"
        camera_image_topic: "/fsds/cam1/image_color"
        # Model params
        model_path: "/home/ros/ws/src/cone_detection/models/Yolov8n1280.onnx"
        classes: [
            "seg_orange_cone", 
            "unknown_cone", 
            "yellow_cone", 
            "seg_large_orange_cone", 
            "seg_blue_cone", 
            "seg_unknown_cone", 
            "seg_yellow_cone", 
            "blue_cone", 
            "orange_cone", 
            "large_orange_cone"
        ]
        width: 1280
        height: 1280
        iou_threshold: 0.5
        rect_confidence_threshold: 0.69
        cuda_enable: true
        log_severity_level: 3
        intra_op_num_threads: 1
        # Lidar-Camera fusion params
        max_len: 26.0
        min_len: 0.01
        interp_factor: 3
        # Lidar-Camera fusion matrices
        camera_matrix: [
            640.0, 0.0  , 640.0, 0.0,
            0.0  , 640.0, 640.0, 0.0,
            0.0  , 0.0  , 1.0  , 0.0
        ]
        rotation_matrix: [
            1.0, 0.0, 0.0,
            0.0, 1.0, 0.0,
            0.0, 0.0, 1.0
        ]
        translation_matrix: [
            0.0,
            0.1,
            0.0
        ]
